version: '3'

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: dockerfile
    image: softy-pinko-back-end:task5
    expose:
      - "5252"

  front-end:
    build:
      context: ./front-end
      dockerfile: dockerfile
    image: softy-pinko-front-end:task5
    expose:
      - "9000"

  proxy:
    build:
      context: ./proxy
      dockerfile: dockerfile
    image: softy-pinko-proxy:task5
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
